### ISSUE TITLE
✨ A new theme for the search engine

### ISSUE THREAD

**Issue by OdoOdeux** [neon-mmd/websurfx#378] opened 2023-11-07 16:32 UTC
### Description

I will work on the front end design of websurfx, and will try to make it look more appealing to the users.

### Do you want to work on this issue?

Yes

### Additional information

I will use html, css and javascript for aforementioned issue.

**Comment by neon-mmd** [comment] 2023-11-07 16:35
Thanks :heart: for taking the time opening this issue. We really appreciate it :+1: as it helps improve the project. Since you have requested to work on the issue. Therefore, we are assigning this issue to you right away :rocket: :slightly_smiling_face: .

**Comment by cybrejon** [comment] 2023-11-29 00:42
I'd like to work on this issue as well and request collaboration.

My plan involves making modifications in `public/static/themes/simple.css` with regards to visual fidelity (margins, padding, color contrast, scale, basic accessibility using pseudo-classes, etc.).

Figma will not be used to present this idea and instead, Stylus (browser extension for injecting css overrides) will be used to provide project members an idea of what I will be after design-wise.

**Comment by neon-mmd** [comment] 2023-11-29 06:23
> I'd like to work on this issue as well and request collaboration.
> 
> My plan involves making modifications in `public/static/themes/simple.css` with regards to visual fidelity (margins, padding, color contrast, scale, basic accessibility using pseudo-classes, etc.).
> 
> Figma will not be used to present this idea and instead, Stylus (browser extension for injecting css overrides) will be used to provide project members an idea of what I will be after design-wise.

Ok great :+1: we have assigned this issue to you to but after reading your plan I find that the plan you are proposing is not what the issue is about like this issue is about writing a completely new theme for the search engine from scratch like for example having a new theme like `neon.css` so after this issue is worked the search engine will have two themes at the end neon theme and simple theme. I hope you got my point :slightly_smiling_face: .

But yes for the plans you proposed I think I would suggest having another issue for it I think it would be better. What do you say?

**Comment by cybrejon** [comment] 2023-11-29 09:51
> But yes for the plans you proposed I think I would suggest having another issue for it I think it would be better. What do you say?

That's true now that you mention it. It has little to do with this issue. I'll go ahead with a separate issue in that case, thanks for pointing that out!

**Comment by cybrejon** [comment] 2023-12-01 09:45
> That's true now that you mention it. It has little to do with this issue. I'll go ahead with a separate issue in that case, thanks for pointing that out!

I wish to clarify some things here.

I have decided to drop involvement on this issue and instead started a new, unrelated one (#405) more fitting to my plans.

Sorry for the misunderstanding folks.

**Comment by neon-mmd** [comment] 2023-12-01 09:49
> > That's true now that you mention it. It has little to do with this issue. I'll go ahead with a separate issue in that case, thanks for pointing that out!
> 
> I wish to clarify some things here.
> 
> I have decided to drop involvement on this issue and instead started a new, unrelated one (#405) more fitting to my plans.
> 
> Sorry for the misunderstanding folks.

Yes sure, no problem, we will de-assign you from this issue right away :rocket: :slightly_smiling_face: . Thanks :heart: for informing us about your decision.

**Comment by neon-mmd** [comment] 2023-12-20 13:43
OdoOdeux, it has been nearly a month, any progress on this issue so far? We would like to know :slightly_smiling_face: .

**Closed as not planned** 2024-05-06 02:08 UTC
Labels: 💻 aspect: code, 🟨 priority: medium, ⭐ goal: addition, 🏁 status: ready for dev, 🕹 aspect: interface, 🔢 points: 5, no-issue-activity
