### ISSUE TITLE
🐛 Nix build fails

### ISSUE THREAD

**Issue by jzbor** [neon-mmd/websurfx#580] opened 2024-06-09 17:06 UTC
### Description

Trying to build the nix flake fails:
```
[jzbor@desktop-i5] ~ nix build github:neon-mmd/websurfx                                        
error: builder for '/nix/store/xlvhl3vqi7k23nxc51f1wa8kprdvg704-websurfx-deps-1.12.1.drv' failed with exit code 101;
       last 10 log lines:
       > [naersk] RUSTFLAGS:
       > [naersk] CARGO_BUILD_RUSTFLAGS:
       > [naersk] CARGO_BUILD_RUSTFLAGS (updated):  --remap-path-prefix /nix/store/66490qh10sfqj2qylj9czkm5y1yh5v3a-crates-io-dependencies=/sources --remap-path-prefix /nix/store/5ns6rp3bm69966l11irsd6z5hd7lp35s-git-dependencies=/sources
       > building
       > cargo build $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
       > error: package `actix-cors v0.7.0` cannot be built because it requires rustc 1.75 or newer, while the currently active rustc version is 1.72.0
       > Either upgrade to rustc 1.75 or newer, or use
       > cargo update -p actix-cors@0.7.0 --precise ver
       > where `ver` is the latest version of `actix-cors` supporting rustc 1.72.0
       > [naersk] cargo returned with exit code 101, exiting
       For full logs, run 'nix log /nix/store/xlvhl3vqi7k23nxc51f1wa8kprdvg704-websurfx-deps-1.12.1.drv'.
error: 1 dependencies of derivation '/nix/store/pn68dhlddsbfjn8w23932yy039w0pj92-websurfx-1.12.1.drv' failed to build
```

### Do you want to work on this issue?

None

**Comment by neon-mmd** [comment] 2024-09-02 16:39
Sorry for the late reply.

Thanks :heart: for taking the time to open this issue. We really appreciate it :+1: as it helps improve our project. :slightly_smiling_face: 

@jfvillablanca @dr460nf1r3 can you folks please help @jzbor with this issue? Because we think you folks might have better idea on this issue 🙂.

**Comment by jfvillablanca** [comment] 2024-09-04 11:42
I currently have a local fix and I can make the PR tomorrow. The issue is that the `flake.lock` is outdated so `rustc` is also outdated.

**Comment by neon-mmd** [comment] 2024-09-04 11:45
> I currently have a local fix and I can make the PR tomorrow. The issue is that the `flake.lock` is outdated so `rustc` is also outdated.

Yes sure, no problem, we will assign this issue to you right away. :rocket: . We would suggest you may start working on it now :slightly_smiling_face:

**Closed as completed** 2024-09-06 05:08 UTC
Labels: 💻 aspect: code, 🛠 goal: fix, 🏁 status: ready for dev, 🔢 points: 3, 🟩 priority: low

**Comment by neon-mmd** [comment] 2024-09-07 18:18
We have now fixed this issue by providing an update for the nix flake but if you still face any issue then we would suggest reopening this issue and providing an update on this issue 🙂 .

**Comment by jzbor** [comment] 2024-09-10 09:58
Thanks alot, it builds now!
