### ISSUE TITLE
🐛 `Libssl.so.3` not found error when running the app in docker 

### ISSUE THREAD

**Issue by huseyinkogo** [neon-mmd/websurfx#197] opened 2023-09-01 01:27 UTC
**Version of Websurfx, commit number if you are using on master branch**
using the latest from the docker file
```
git log -1
``` 
-->

**How did you install Websurfx?**
With the docker compose.
nothing has been changed default docker-compose.yml & config.lua

**What happened?**
getting the following logs;

```
vn@v428:~/docker/websurfx$ docker logs -f websurfx
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

```

**Comment by neon-mmd** [comment] 2023-09-03 07:54
> **Version of Websurfx, commit number if you are using on master branch** using the latest from the docker file
> 
> ```
> git log -1
> ```
> 
> -->
> 
> **How did you install Websurfx?** With the docker compose. nothing has been changed default docker-compose.yml & config.lua
> 
> **What happened?** getting the following logs;
> 
> ```
> vn@v428:~/docker/websurfx$ docker logs -f websurfx
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> websurfx: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> ```

Sorry for the late reply, actually we are right now busy working on getting the first release that's why we aren't able to reply to you. But Also thanks :heart: for taking the time to report this issue. It really helps us improve this project, so we really appreciate it :+1: . 

After testing it on my side, it seems that it works for me. I don't get this error. Can you provide some more context on what steps you followed to deploy the app? Like, did you add any additional step or anything ?

Also, I would suggest trying the below provided Dockerfile and let us know if it solves the problem.

``` dockerfile
FROM rust:latest AS chef
# We only pay the installation cost once,
# it will be cached from the second build onwards
RUN cargo install cargo-chef

WORKDIR /app

FROM chef AS planner
COPY . . 
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json

# Build application
COPY . .
RUN cargo install --path .

# We do not need the Rust toolchain to run the binary!
FROM gcr.io/distroless/cc-debian12
COPY --from=builder /app/public/ /opt/websurfx/public/
COPY --from=builder /app/websurfx/config.lua /etc/xdg/websurfx/config.lua
COPY --from=builder /usr/local/cargo/bin/* /usr/local/bin/
CMD ["websurfx"]
```

**Comment by kyoruno** [comment] 2023-09-03 17:09
Can confirm moving to `cc-debian12` resolves the issue.

**Comment by neon-mmd** [comment] 2023-09-03 18:17
> Can confirm moving to `cc-debian12` resolves the issue.

Thanks :heart: for the feedback, this is good to hear, but what about you [huseyinkogo](https://github.com/huseyinkogo)? We would like to know. :slightly_smiling_face:

**Comment by huseyinkogo** [comment] 2023-09-08 04:15
@neon-mmd 
Sorry been sick for the past days. However it doesn;t work on the moving to `cc-debian12`

Now getting this log after moving to  `cc-debian12`

```
in@v4:~/docker/websurfx$ docker logs -f websurfx-app-1 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversionError { from: "nil", to: "String", message: Some("expected string or number") }', src/bin/websurfx.rs:18:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by neon-mmd** [comment] 2023-09-08 18:31
> @neon-mmd Sorry been sick for the past days. However it doesn;t work on the moving to `cc-debian12`

Sorry to hear. Hope you get well soon.  

> Now getting this log after moving to `cc-debian12`
> 
> ```
> in@v4:~/docker/websurfx$ docker logs -f websurfx-app-1 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversionError { from: "nil", to: "String", message: Some("expected string or number") }', src/bin/websurfx.rs:18:39
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

I think there is an incorrect configuration value added somewhere, which is why this error is occurring. So, If you don't mind, can you provide your config file here ? Because I guess this will better allow us to pinpoint the issue and resolve it. :slightly_smiling_face:

**Comment by huseyinkogo** [comment] 2023-09-09 10:21
@neon-mmd thanks so much mate :)

sure below is the websurfx/config.lua
```

-- ### General ###
logging = true -- an option to enable or disable logs.
debug = false -- an option to enable or disable debug mode.
threads = 10 -- the amount of threads that the app will use to run (the value should be greater than 0).

-- ### Server ###
port = "8080" -- port on which server should be launched
binding_ip = "0.0.0.0" --ip address on the which server should be launched.
production_use = false -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users (more than one))
-- if production_use is set to true
-- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.
request_timeout = 60 -- timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).

-- ### Website ###
-- The different colorschemes provided are:
-- {{
-- catppuccin-mocha
-- dark-chocolate
-- dracula
-- gruvbox-dark
-- monokai
-- nord
-- oceanic-next
-- one-dark
-- solarized-dark
-- solarized-light
-- tokyo-night
-- tomorrow-night
-- }}
colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
theme = "simple" -- the theme name which should be used for the website

-- ### Caching ###
redis_connection_url = "redis://redis:6379" -- redis connection url address on which the client should connect on.

-- ### Search Engines ###
upstream_search_engines = { DuckDuckGo = true, Searx = false } -- select the upstream search engines from which the results should be fetched.

```

**Comment by neon-mmd** [comment] 2023-09-09 15:51
> @neon-mmd thanks so much mate :)
> 
> sure below is the websurfx/config.lua
> 
> ```
> 
> -- ### General ###
> logging = true -- an option to enable or disable logs.
> debug = false -- an option to enable or disable debug mode.
> threads = 10 -- the amount of threads that the app will use to run (the value should be greater than 0).
> 
> -- ### Server ###
> port = "8080" -- port on which server should be launched
> binding_ip = "0.0.0.0" --ip address on the which server should be launched.
> production_use = false -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users (more than one))
> -- if production_use is set to true
> -- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.
> request_timeout = 60 -- timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).
> 
> -- ### Website ###
> -- The different colorschemes provided are:
> -- {{
> -- catppuccin-mocha
> -- dark-chocolate
> -- dracula
> -- gruvbox-dark
> -- monokai
> -- nord
> -- oceanic-next
> -- one-dark
> -- solarized-dark
> -- solarized-light
> -- tokyo-night
> -- tomorrow-night
> -- }}
> colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
> theme = "simple" -- the theme name which should be used for the website
> 
> -- ### Caching ###
> redis_connection_url = "redis://redis:6379" -- redis connection url address on which the client should connect on.
> 
> -- ### Search Engines ###
> upstream_search_engines = { DuckDuckGo = true, Searx = false } -- select the upstream search engines from which the results should be fetched.
> ```

Ok, I got where the problem is, and I am really sorry for that, I think there is a small typo I introduced within the config file I provided in the docs. I think I will fix it as soon as possible. The typo is that in the config file the `redis_connection_url` should actually be `redis_url` but mistakenly I wrote `redis_connection_url`. So that's why you are getting the error. So the config file should look like this:

``` lua
-- ### General ###
logging = true -- an option to enable or disable logs.
debug = false -- an option to enable or disable debug mode.
threads = 10 -- the amount of threads that the app will use to run (the value should be greater than 0).

-- ### Server ###
port = "8080" -- port on which server should be launched
binding_ip = "0.0.0.0" --ip address on the which server should be launched.
production_use = false -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users (more than one))
-- if production_use is set to true
-- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.
request_timeout = 60 -- timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).

-- ### Website ###
-- The different colorschemes provided are:
-- {{
-- catppuccin-mocha
-- dark-chocolate
-- dracula
-- gruvbox-dark
-- monokai
-- nord
-- oceanic-next
-- one-dark
-- solarized-dark
-- solarized-light
-- tokyo-night
-- tomorrow-night
-- }}
colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
theme = "simple" -- the theme name which should be used for the website

-- ### Caching ###
redis_url = "redis://redis:6379" -- redis connection url address on which the client should connect on.

-- ### Search Engines ###
upstream_search_engines = { DuckDuckGo = true, Searx = false } -- select the upstream search engines from which the results should be fetched.
```

So I would suggest replacing your config file with the one I provided and this will fix the issue :slightly_smiling_face: .

**Comment by huseyinkogo** [comment] 2023-09-11 12:39
@neon-mmd 
heheheh dont need to be sorry, it happens sometimes.

so got it working however i can't even do searchs, it says "BlockList file not found!!"
![image](https://github.com/neon-mmd/websurfx/assets/76049382/fbe47e97-5c33-4659-b144-86d399cd07c5)

Docker logs (websurfx-app-1)

```
vhuseyin@v4:~/docker/websurfx$ docker logs -f websurfx-app-1
[2023-09-11T12:16:10Z INFO  websurfx] started server on port 8080 and IP 0.0.0.0
[2023-09-11T12:16:10Z INFO  websurfx] Open http://0.0.0.0:8080/ in your browser
[2023-09-11T12:16:10Z INFO  actix_server::builder] starting 10 workers
[2023-09-11T12:16:10Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET / HTTP/1.1" 200 1466 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000209
[2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/colorschemes/catppuccin-mocha.css HTTP/1.1" 200 246 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000707
[2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/themes/simple.css HTTP/1.1" 200 9896 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000586
[2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/settings.js HTTP/1.1" 200 3925 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000565
[2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/index.js HTTP/1.1" 200 626 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000610
[2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /images/websurfx_logo.png HTTP/1.1" 200 8264 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000426
[2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /favicon.ico HTTP/1.1" 200 1349 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000088
[2023-09-11T12:24:02Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /settings HTTP/1.1" 200 4617 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000161
[2023-09-11T12:24:03Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/cookies.js HTTP/1.1" 200 1170 "http://10.20.2.154:8080/settings" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000400
[2023-09-11T12:24:16Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET / HTTP/1.1" 200 1466 "http://10.20.2.154:8080/settings" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000116
[2023-09-11T12:26:52Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /search?q=chatgpt HTTP/1.1" 500 26 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 15.192505
[2023-09-11T12:30:14Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /settings HTTP/1.1" 200 4617 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000131
[2023-09-11T12:30:15Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /search?q=google HTTP/1.1" 500 26 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 12.898119
[2023-09-11T12:30:21Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET / HTTP/1.1" 200 1466 "http://10.20.2.154:8080/settings" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000121
[2023-09-11T12:30:39Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /search?q=google HTTP/1.1" 500 26 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 12.843679
^Z
[2]+  Stopped                 docker logs -f websurfx-app-1
```
Docker logs (websurfx-redis-1)
```

vhuseyin@v4:~/docker/websurfx$ docker logs -f websurfx-redis-1
1:C 11 Sep 2023 12:16:11.556 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 11 Sep 2023 12:16:11.557 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Sep 2023 12:16:11.557 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Sep 2023 12:16:11.557 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 11 Sep 2023 12:16:11.557 * monotonic clock: POSIX clock_gettime
1:M 11 Sep 2023 12:16:11.558 * Running mode=standalone, port=6379.
1:M 11 Sep 2023 12:16:11.558 * Server initialized
1:M 11 Sep 2023 12:16:11.558 * Ready to accept connections tcp

```

**Comment by neon-mmd** [comment] 2023-09-11 16:14
> @neon-mmd heheheh dont need to be sorry, it happens sometimes.
> 
> so got it working however i can't even do searchs, it says "BlockList file not found!!" ![image](https://user-images.githubusercontent.com/76049382/267020271-fbe47e97-5c33-4659-b144-86d399cd07c5.png)
> 
> Docker logs (websurfx-app-1)
> 
> ```
> vhuseyin@v4:~/docker/websurfx$ docker logs -f websurfx-app-1
> [2023-09-11T12:16:10Z INFO  websurfx] started server on port 8080 and IP 0.0.0.0
> [2023-09-11T12:16:10Z INFO  websurfx] Open http://0.0.0.0:8080/ in your browser
> [2023-09-11T12:16:10Z INFO  actix_server::builder] starting 10 workers
> [2023-09-11T12:16:10Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
> [2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET / HTTP/1.1" 200 1466 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000209
> [2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/colorschemes/catppuccin-mocha.css HTTP/1.1" 200 246 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000707
> [2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/themes/simple.css HTTP/1.1" 200 9896 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000586
> [2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/settings.js HTTP/1.1" 200 3925 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000565
> [2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/index.js HTTP/1.1" 200 626 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000610
> [2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /images/websurfx_logo.png HTTP/1.1" 200 8264 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000426
> [2023-09-11T12:23:32Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /favicon.ico HTTP/1.1" 200 1349 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000088
> [2023-09-11T12:24:02Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /settings HTTP/1.1" 200 4617 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000161
> [2023-09-11T12:24:03Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /static/cookies.js HTTP/1.1" 200 1170 "http://10.20.2.154:8080/settings" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000400
> [2023-09-11T12:24:16Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET / HTTP/1.1" 200 1466 "http://10.20.2.154:8080/settings" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000116
> [2023-09-11T12:26:52Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /search?q=chatgpt HTTP/1.1" 500 26 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 15.192505
> [2023-09-11T12:30:14Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /settings HTTP/1.1" 200 4617 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000131
> [2023-09-11T12:30:15Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /search?q=google HTTP/1.1" 500 26 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 12.898119
> [2023-09-11T12:30:21Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET / HTTP/1.1" 200 1466 "http://10.20.2.154:8080/settings" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 0.000121
> [2023-09-11T12:30:39Z INFO  actix_web::middleware::logger] 10.20.3.3 "GET /search?q=google HTTP/1.1" 500 26 "http://10.20.2.154:8080/" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0" 12.843679
> ^Z
> [2]+  Stopped                 docker logs -f websurfx-app-1
> ```
> 
> Docker logs (websurfx-redis-1)
> 
> ```
> 
> vhuseyin@v4:~/docker/websurfx$ docker logs -f websurfx-redis-1
> 1:C 11 Sep 2023 12:16:11.556 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> 1:C 11 Sep 2023 12:16:11.557 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 1:C 11 Sep 2023 12:16:11.557 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
> 1:C 11 Sep 2023 12:16:11.557 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
> 1:M 11 Sep 2023 12:16:11.557 * monotonic clock: POSIX clock_gettime
> 1:M 11 Sep 2023 12:16:11.558 * Running mode=standalone, port=6379.
> 1:M 11 Sep 2023 12:16:11.558 * Server initialized
> 1:M 11 Sep 2023 12:16:11.558 * Ready to accept connections tcp
> ```

Ok, I got the error, and I am sorry once again. We are going to get the docs updated soon because this feature was added very recently, so we are in the process of updating the docs but meanwhile I would suggest trying out this updated `dockerfile` here:

``` dockerfile
FROM rust:latest AS chef
# We only pay the installation cost once,
# it will be cached from the second build onwards
RUN cargo install cargo-chef

WORKDIR /app

FROM chef AS planner
COPY . . 
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json

# Build application
COPY . .
RUN cargo install --path .

# We do not need the Rust toolchain to run the binary!
FROM gcr.io/distroless/cc-debian12
COPY --from=builder /app/public/ /opt/websurfx/public/
COPY --from=builder /app/websurfx/config.lua /etc/xdg/websurfx/config.lua
COPY --from=builder /app/websurfx/config.lua /etc/xdg/websurfx/allowlist.txt
COPY --from=builder /app/websurfx/config.lua /etc/xdg/websurfx/blocklist.txt
COPY --from=builder /usr/local/cargo/bin/* /usr/local/bin/
CMD ["websurfx"]
```

By using this `Dockerfile` it will solve your problem :slightly_smiling_face: .

**Comment by neon-mmd** [comment] 2023-09-23 14:46
@huseyinkogo Two weeks has been passed. So we want to know whether your issue got fixed or not ? should we close this issue now ? 🙂

**Comment by neon-mmd** [comment] 2023-10-01 18:26
@huseyinkogo, We are closing this issue as there is no activity on this issue for a long time, but if you are problem has still not resolved then we would suggest reopening this issue in the future :slightly_smiling_face: . Also, thanks :heart: again for opening this issue :slightly_smiling_face: .

**Closed as completed by neon-mmd** 2023-10-01 18:26 UTC
Labels: 🟧 priority: high, 💻 aspect: code, 🛠 goal: fix, 🔢 points: 2, no-issue-activity
